FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y apt-utils git rsync nano vim unzip curl wget \
    software-properties-common default-mysql-client apache2 \
    && rm -rf /var/lib/apt/lists/*

RUN ln -snf /usr/share/zoneinfo/UTC /etc/localtime \
    && echo "UTC" > /etc/timezone

ENV APACHE_RUN_USER="www-data" \
    APACHE_RUN_GROUP="www-data" \
    APACHE_LOG_DIR="/var/log/apache2"

RUN chown -R www-data:www-data /var/www \
    && chmod -R 755 /var/www

RUN a2enmod rewrite \
    && a2enmod headers

WORKDIR /var/www/html
COPY . .

EXPOSE 80

CMD ["apache2ctl", "-D", "FOREGROUND"]